## 2.1.3 Broadcasting Mechanism

In [1]:
import torch

/run/media/gt610/86E787FB42ED6C4E/Data/个人/学习笔记/动手学深度学习/.venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


Create two tensors, one 3\*1, the other 1\*2

In [4]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

`a+b` will automatically broadcast these two tensors to the same shape.

The steps are below:
1. Copy the columns of a. Now a: `[ [0,0],[1,1],[2,2] ]`
2. Copy the lines of b. Now b: `[ [0,1],[0,1],[0,1] ]`
3. Now they are all 3*2. It's time to add them together.

In [5]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])