## 2.1.1 Get started

In [4]:
import torch

/run/media/gt610/86E787FB42ED6C4E/Data/个人/学习笔记/动手学深度学习/.venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


Create a line vector $x$ ranging from 0 to 12

In [5]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Get the tensor's shape through accessing `shape` attribution

In [6]:
x.shape

torch.Size([12])

Get the size of the tensor by getting all elements' production

In [7]:
x.numel()

12

Change the shape of the tensor to a 3*4 matrix, but do not change the elements

In [8]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Create a all-zero 2\*3\*4 matrix

In [9]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Similiarly we can create a all-one 2\*3\*4 matrix

In [10]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Generate a random 0-1 normal distribution 3*4 tensor

In [11]:
torch.randn(3,4)

tensor([[ 0.1058, -0.5728, -0.8954,  1.8250],
        [ 0.1677, -0.8991,  0.6185,  0.2023],
        [ 1.8016, -0.7933, -1.0660,  1.5622]])

Specify every element by passing a nested list

In [12]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])