## 2.1.6 Convert to other Python objects

In [7]:
import torch
import numpy as np

In [8]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

Convert from tensor to ndarray, and then convert it back

In [9]:
A=X.numpy()
B=torch.Tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

We can slao convert one-element tensor into a regular Python number type.

In [10]:
a=torch.Tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## Exercise

In [12]:
X,Y
X==Y,X>Y,X<Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))